import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "@/app/globals.css";
import NextAuthWarpper from "@/library/next-auth.warpper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thuan HRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <NextAuthWarpper>{children}</NextAuthWarpper>
        </AntdRegistry>
      </body>
    </html>
  );
}
